import { Injectable, computed, effect, inject, signal } from '@angular/core';
import { CatalogService } from '../../core/catalog.service';

export type OrderStatus = 'pendingPayment' | 'paid' | 'preparing' | 'shipped' | 'delivered' | 'collected' | 'cancelled';
export type CustomerType = 'Particular' | 'Restaurante' | 'Distribuidor';
export interface AdminProduct { id:string; reference:string; name:string; category:string; price:number; vatRate:number; stock:number; reserved:number; sales:number; active:boolean; updatedAt:string; }
export interface OrderLine { product:string; reference:string; quantity:number; unitPrice:number; }
export interface AdminOrder { id:string; number:string; customer:string; email:string; city:string; province:string; date:string; isoDate:string; total:number; items:number; status:OrderStatus; payment:'succeeded'|'pending'|'refunded'; channel:'Web'|'Bodega'|'Restauración'; address:string; postalCode:string; carrier:string; notes:string; lines:OrderLine[]; }
export interface AdminCustomer { id:string; name:string; email:string; phone:string; city:string; province:string; type:CustomerType; orders:number; spent:number; annualSpent:number; lastOrder:string; segment:'Nuevo'|'Recurrente'|'Top cliente'; discount:number; notes:string; active:boolean; }
export interface AdminVisit { id:string; customer:string; email:string; type:string; date:string; isoDate:string; time:string; people:number; status:'confirmed'|'pending'|'cancelled'; payment:'paid'|'pending'|'refunded'; amount:number; previousVisits:number; notes:string; }
export interface AdminInvoice { id:string; number:string; customer:string; issueDate:string; isoDate:string; total:number; tax:number; status:'issued'|'draft'|'rectified'; verifactu:'accepted'|'pending'|'error'; orderNumber:string; lines:OrderLine[]; }
export interface SalesPoint { label:string; revenue:number; expenses:number; orders:number; visits:number; }
export interface Coupon { id:string; code:string; type:'percentage'|'fixed'; value:number; uses:number; active:boolean; }
export interface WeeklyTask { id:string; title:string; due:string; done:boolean; }
const line=(product:string,reference:string,quantity:number,unitPrice:number):OrderLine=>({product,reference,quantity,unitPrice});
const products:AdminProduct[]=[
 {id:'p1',reference:'DOM-CRZ-01',name:'Dominium Crianza',category:'Tintos',price:18.9,vatRate:21,stock:46,reserved:8,sales:124,active:true,updatedAt:'29 sep, 10:42'},
 {id:'p2',reference:'MOM-ROB-01',name:'Momentum Roble',category:'Tintos',price:14.5,vatRate:21,stock:12,reserved:5,sales:98,active:true,updatedAt:'29 sep, 09:16'},
 {id:'p3',reference:'DS-BLA-01',name:'Dominio de la Sierra Blanco',category:'Blancos',price:16.75,vatRate:21,stock:31,reserved:3,sales:71,active:true,updatedAt:'28 sep, 17:04'},
 {id:'p4',reference:'RUF-ANS-01',name:'Rufete Ancestral',category:'Ancestral',price:21.9,vatRate:21,stock:7,reserved:4,sales:143,active:true,updatedAt:'28 sep, 12:20'},
 {id:'p5',reference:'DS-PACK-03',name:'Caja Paisaje de la Sierra',category:'Packs',price:54,vatRate:21,stock:18,reserved:2,sales:39,active:true,updatedAt:'27 sep, 18:41'},
 {id:'p6',reference:'RUF-ROS-20',name:'Rufete Rosado 2020',category:'Archivo',price:15.9,vatRate:21,stock:0,reserved:0,sales:28,active:false,updatedAt:'14 sep, 11:07'}];
const orders:AdminOrder[]=[
 {id:'o1',number:'DS-2026-000184',customer:'Marta García',email:'marta.garcia@example.com',city:'Madrid',province:'Madrid',date:'29 sep · 11:48',isoDate:'2026-09-29',total:92.3,items:5,status:'preparing',payment:'succeeded',channel:'Web',address:'C/ Alcalá, 118 · 3º B',postalCode:'28009',carrier:'Correos Express',notes:'Entregar por la tarde.',lines:[line('Dominium Crianza','DOM-CRZ-01',3,18.9),line('Dominio de la Sierra Blanco','DS-BLA-01',2,16.75)]},
 {id:'o2',number:'DS-2026-000183',customer:'Carlos Núñez',email:'carlos.n@example.com',city:'Salamanca',province:'Salamanca',date:'29 sep · 10:21',isoDate:'2026-09-29',total:43.8,items:2,status:'paid',payment:'succeeded',channel:'Web',address:'Paseo Canalejas, 41',postalCode:'37001',carrier:'Pendiente de asignar',notes:'',lines:[line('Rufete Ancestral','RUF-ANS-01',2,21.9)]},
 {id:'o3',number:'DS-2026-000182',customer:'Lucía Martín',email:'lucia.m@example.com',city:'Valladolid',province:'Valladolid',date:'29 sep · 09:05',isoDate:'2026-09-29',total:68.65,items:4,status:'pendingPayment',payment:'pending',channel:'Web',address:'C/ Santiago, 22',postalCode:'47001',carrier:'Sin asignar',notes:'Pago pendiente en Stripe.',lines:[line('Momentum Roble','MOM-ROB-01',3,14.5),line('Dominio de la Sierra Blanco','DS-BLA-01',1,16.75)]},
 {id:'o4',number:'DS-2026-000181',customer:'Restaurante Arca',email:'compras@arca.example',city:'León',province:'León',date:'28 sep · 18:37',isoDate:'2026-09-28',total:248.4,items:12,status:'shipped',payment:'succeeded',channel:'Restauración',address:'Av. Ordoño II, 16',postalCode:'24001',carrier:'SEUR · 00488216',notes:'Recepción de mercancía hasta las 13:00.',lines:[line('Dominium Crianza','DOM-CRZ-01',6,17.5),line('Rufete Ancestral','RUF-ANS-01',6,19.9)]},
 {id:'o5',number:'DS-2026-000180',customer:'Javier Gil',email:'javier.gil@example.com',city:'Barcelona',province:'Barcelona',date:'28 sep · 16:12',isoDate:'2026-09-28',total:37.8,items:2,status:'delivered',payment:'succeeded',channel:'Web',address:'C/ Girona, 87',postalCode:'08009',carrier:'MRW · 873025',notes:'',lines:[line('Dominium Crianza','DOM-CRZ-01',2,18.9)]},
 {id:'o6',number:'DS-2026-000179',customer:'Ana Rivas',email:'ana.rivas@example.com',city:'Cáceres',province:'Cáceres',date:'28 sep · 12:54',isoDate:'2026-09-28',total:76.7,items:4,status:'cancelled',payment:'refunded',channel:'Web',address:'Av. España, 9',postalCode:'10001',carrier:'Cancelado',notes:'Reembolso procesado.',lines:[line('Momentum Roble','MOM-ROB-01',2,14.5),line('Dominium Crianza','DOM-CRZ-01',1,18.9),line('Rufete Ancestral','RUF-ANS-01',1,21.9)]}];
const customers:AdminCustomer[]=[
 {id:'c1',name:'Restaurante Arca',email:'compras@arca.example',phone:'+34 987 221 480',city:'León',province:'León',type:'Restaurante',orders:18,spent:2849.2,annualSpent:2260,lastOrder:'28 sep 2026',segment:'Top cliente',discount:12,notes:'Tarifa horeca. Entregas antes de las 13:00.',active:true},
 {id:'c2',name:'Marta García',email:'marta.garcia@example.com',phone:'+34 610 248 328',city:'Madrid',province:'Madrid',type:'Particular',orders:11,spent:1032.6,annualSpent:814,lastOrder:'29 sep 2026',segment:'Top cliente',discount:5,notes:'Miembro del club de la bodega.',active:true},
 {id:'c3',name:'Casa Méndez',email:'pedidos@casamendez.example',phone:'+34 923 554 120',city:'Salamanca',province:'Salamanca',type:'Distribuidor',orders:9,spent:876.4,annualSpent:876.4,lastOrder:'24 sep 2026',segment:'Recurrente',discount:15,notes:'Pedido mínimo de 24 botellas.',active:true},
 {id:'c4',name:'Lucía Martín',email:'lucia.m@example.com',phone:'+34 644 120 334',city:'Valladolid',province:'Valladolid',type:'Particular',orders:4,spent:302.15,annualSpent:238,lastOrder:'29 sep 2026',segment:'Recurrente',discount:0,notes:'',active:true},
 {id:'c5',name:'Carlos Núñez',email:'carlos.n@example.com',phone:'+34 699 550 221',city:'Salamanca',province:'Salamanca',type:'Particular',orders:1,spent:43.8,annualSpent:43.8,lastOrder:'29 sep 2026',segment:'Nuevo',discount:0,notes:'',active:true}];
const visits:AdminVisit[]=[
 {id:'v1',customer:'Paula Sanz',email:'paula.sanz@example.com',type:'Viñedo, bodega y cata',date:'30 sep',isoDate:'2026-09-30',time:'11:00',people:4,status:'confirmed',payment:'paid',amount:72,previousVisits:1,notes:'Una persona vegetariana.'},
 {id:'v2',customer:'Grupo Sierra Viva',email:'reservas@sierraviva.example',type:'Experiencia Rufete',date:'30 sep',isoDate:'2026-09-30',time:'17:00',people:8,status:'confirmed',payment:'paid',amount:176,previousVisits:2,notes:'Grupo privado.'},
 {id:'v3',customer:'Álvaro Rey',email:'alvaro.rey@example.com',type:'Visita esencial',date:'2 oct',isoDate:'2026-10-02',time:'12:30',people:2,status:'pending',payment:'pending',amount:36,previousVisits:0,notes:''},
 {id:'v4',customer:'María Teresa López',email:'mtlopez@example.com',type:'Viñedo, bodega y cata',date:'3 oct',isoDate:'2026-10-03',time:'11:00',people:5,status:'confirmed',payment:'paid',amount:90,previousVisits:3,notes:'Celebración de aniversario.'}];
const invoices:AdminInvoice[]=[
 {id:'i1',number:'A-2026-00172',customer:'Restaurante Arca',issueDate:'28 sep 2026',isoDate:'2026-09-28',total:248.4,tax:43.12,status:'issued',verifactu:'accepted',orderNumber:'DS-2026-000181',lines:orders[3].lines},
 {id:'i2',number:'A-2026-00171',customer:'Javier Gil',issueDate:'28 sep 2026',isoDate:'2026-09-28',total:37.8,tax:6.56,status:'issued',verifactu:'accepted',orderNumber:'DS-2026-000180',lines:orders[4].lines},
 {id:'i3',number:'BORRADOR',customer:'Marta García',issueDate:'29 sep 2026',isoDate:'2026-09-29',total:92.3,tax:16.02,status:'draft',verifactu:'pending',orderNumber:'DS-2026-000184',lines:orders[0].lines},
 {id:'i4',number:'R-2026-00004',customer:'Ana Rivas',issueDate:'28 sep 2026',isoDate:'2026-09-28',total:-76.7,tax:-13.31,status:'rectified',verifactu:'pending',orderNumber:'DS-2026-000179',lines:orders[5].lines}];

@Injectable({providedIn:'root'}) export class AdminDataService {
 private readonly catalog=inject(CatalogService); private readonly productsSignal=signal(products); private readonly ordersSignal=signal(orders); private readonly customersSignal=signal(customers); private readonly visitsSignal=signal(visits); private readonly invoicesSignal=signal(invoices);
 readonly products=this.productsSignal.asReadonly(); readonly orders=this.ordersSignal.asReadonly(); readonly customers=this.customersSignal.asReadonly(); readonly visits=this.visitsSignal.asReadonly(); readonly invoices=this.invoicesSignal.asReadonly();
 readonly coupons=signal<Coupon[]>([{id:'cp1',code:'SIERRA10',type:'percentage',value:10,uses:42,active:true},{id:'cp2',code:'VISITA5',type:'fixed',value:5,uses:18,active:true},{id:'cp3',code:'NAVIDAD23',type:'percentage',value:15,uses:87,active:false}]);
 readonly tasks=signal<WeeklyTask[]>([{id:'t1',title:'Preparar pedido DS-2026-000184',due:'Hoy · 13:00',done:false},{id:'t2',title:'Confirmar visita de Álvaro Rey',due:'Hoy · 17:00',done:false},{id:'t3',title:'Revisar stock de Rufete Ancestral',due:'Mañana',done:false}]);
 readonly sales=signal<SalesPoint[]>([{label:'Abr',revenue:4820,expenses:2110,orders:62,visits:38},{label:'May',revenue:5640,expenses:2340,orders:71,visits:52},{label:'Jun',revenue:5210,expenses:2280,orders:67,visits:61},{label:'Jul',revenue:6890,expenses:2810,orders:84,visits:83},{label:'Ago',revenue:7420,expenses:3050,orders:91,visits:96},{label:'Sep',revenue:8314,expenses:3270,orders:108,visits:74}]).asReadonly();
 readonly revenue=computed(()=>this.sales().at(-1)?.revenue??0); readonly orderCount=computed(()=>this.sales().at(-1)?.orders??0); readonly averageTicket=computed(()=>this.orderCount()?this.revenue()/this.orderCount():0); readonly lowStockCount=computed(()=>this.products().filter(i=>i.active&&i.stock-i.reserved<=10).length);
 constructor(){effect(()=>{const live=this.catalog.products();if(!live.length)return;this.productsSignal.update(current=>live.map((p,index)=>{const e=current.find(i=>i.id===p.id||i.reference===p.reference);return{id:p.id,reference:p.reference,name:p.name,category:p.categoryName,price:p.price,vatRate:21,stock:e?.stock??Math.max(4,38-index*5),reserved:e?.reserved??index%4,sales:e?.sales??20+index*13,active:e?.active??true,updatedAt:e?.updatedAt??'Sincronizado ahora'};}));});}
 toggleProduct(id:string){this.productsSignal.update(items=>items.map(i=>i.id===id?{...i,active:!i.active,updatedAt:'Ahora'}:i));} adjustStock(id:string,q:number){this.productsSignal.update(items=>items.map(i=>i.id===id?{...i,stock:Math.max(i.reserved,i.stock+q),updatedAt:'Ahora'}:i));}
 addProduct(product:Omit<AdminProduct,'id'|'sales'|'reserved'|'updatedAt'>){this.productsSignal.update(items=>[{...product,id:`local-${Date.now()}`,sales:0,reserved:0,updatedAt:'Ahora'},...items]);} setOrderStatus(id:string,status:OrderStatus){this.ordersSignal.update(items=>items.map(i=>i.id===id?{...i,status}:i));}
 updateProduct(id:string,product:Omit<AdminProduct,'id'|'sales'|'reserved'|'updatedAt'>){this.productsSignal.update(items=>items.map(item=>item.id===id?{...item,...product,stock:Math.max(item.reserved,product.stock),updatedAt:'Ahora'}:item));}
 saveCustomer(customer:AdminCustomer){this.customersSignal.update(items=>items.some(i=>i.id===customer.id)?items.map(i=>i.id===customer.id?customer:i):[customer,...items]);} toggleCustomer(id:string){this.customersSignal.update(items=>items.map(i=>i.id===id?{...i,active:!i.active}:i));}
 addVisit(visit:AdminVisit){this.visitsSignal.update(items=>[visit,...items]);} toggleTask(id:string){this.tasks.update(items=>items.map(i=>i.id===id?{...i,done:!i.done}:i));} toggleCoupon(id:string){this.coupons.update(items=>items.map(i=>i.id===id?{...i,active:!i.active}:i));}
}
