import { CommonModule } from '@angular/common';
import { Component, OnDestroy, computed, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { DismissOutsideDirective } from '../../shared/dismiss-outside.directive';
import { ActivatedRoute, Router } from '@angular/router';
import { Subscription } from 'rxjs';
import { AdminCustomer, AdminDataService, AdminInvoice, AdminOrder, AdminProduct, AdminVisit, OrderStatus } from './admin-data.service';

type AdminSection='overview'|'orders'|'catalog'|'inventory'|'customers'|'finance'|'visits'|'billing'|'settings';
interface NavigationItem{id:AdminSection;label:string;caption:string;icon:string;}
@Component({selector:'ds-admin-dashboard',standalone:true,imports:[CommonModule,FormsModule,DismissOutsideDirective],templateUrl:'./admin-dashboard.component.html',styleUrl:'./admin-dashboard.component.scss'})
export class AdminDashboardComponent implements OnDestroy {
 readonly navItems:NavigationItem[]=[
  {id:'overview',label:'Resumen',caption:'Pulso del negocio',icon:'home'},{id:'orders',label:'Pedidos',caption:'Preparación y envíos',icon:'orders'},{id:'catalog',label:'Catálogo',caption:'Vinos y precios',icon:'bottle'},{id:'inventory',label:'Inventario',caption:'Stock y almacén',icon:'boxes'},{id:'customers',label:'Clientes',caption:'Relación y territorio',icon:'users'},{id:'finance',label:'Finanzas',caption:'Ventas y cobros',icon:'chart'},{id:'visits',label:'Visitas',caption:'Agenda de bodega',icon:'calendar'},{id:'billing',label:'Facturación',caption:'Facturas y VeriFactu',icon:'invoice'},{id:'settings',label:'Ajustes',caption:'Empresa y preferencias',icon:'settings'}];
 readonly section=signal<AdminSection>('overview'); readonly mobileMenuOpen=signal(false); readonly productPanelOpen=signal(false); readonly notificationsOpen=signal(false); readonly searchOpen=signal(false); readonly selectedOrder=signal<AdminOrder|null>(null); readonly selectedCustomer=signal<AdminCustomer|null>(null); readonly selectedVisit=signal<AdminVisit|null>(null); readonly selectedInvoice=signal<AdminInvoice|null>(null); readonly customerPanelOpen=signal(false); readonly visitPanelOpen=signal(false); readonly productMenu=signal<string|null>(null); readonly region=signal('Todas');
 orderFilter='all'; orderQuery=''; orderFrom=''; orderTo=''; orderMin:number|null=null; orderMax:number|null=null; productQuery=''; productCategory='Todas'; productStock='all'; productStatus='all'; stockQuery=''; customerQuery=''; customerType='Todos'; customerMinSpend:number|null=null; financeRange='6m'; invoiceQuery=''; invoiceStatus='all'; invoiceFrom=''; invoiceTo=''; invoiceMin:number|null=null; invoiceMax:number|null=null; globalQuery=''; fontScale=100; annualGoal=10000; minimumNotice=2; blockedDays='lunes, martes, miércoles'; blockedHours='14:00–16:30'; defaultVat=21;
 readonly notice=signal(''); readonly selectedProductId=signal<string|null>(null);
 productDraft=this.emptyProduct(); customerDraft=this.emptyCustomer(); visitDraft=this.emptyVisit();
 readonly currentNavigation=computed(()=>this.navItems.find(i=>i.id===this.section())??this.navItems[0]);
 readonly filteredOrders=()=>{const q=this.orderQuery.trim().toLowerCase();return this.data.orders().filter(o=>(this.orderFilter==='all'||o.status===this.orderFilter)&&(!q||`${o.number} ${o.customer} ${o.email}`.toLowerCase().includes(q))&&(!this.orderFrom||o.isoDate>=this.orderFrom)&&(!this.orderTo||o.isoDate<=this.orderTo)&&(this.orderMin===null||o.total>=this.orderMin)&&(this.orderMax===null||o.total<=this.orderMax));};
 readonly filteredProducts=()=>{const q=this.productQuery.trim().toLowerCase();return this.data.products().filter(p=>(!q||`${p.name} ${p.reference}`.toLowerCase().includes(q))&&(this.productCategory==='Todas'||p.category===this.productCategory)&&(this.productStatus==='all'||this.productStatus==='active'&&p.active||this.productStatus==='inactive'&&!p.active)&&(this.productStock==='all'||this.productStock==='low'&&this.available(p)<=10||this.productStock==='healthy'&&this.available(p)>10));};
 readonly filteredStock=()=>{const q=this.stockQuery.trim().toLowerCase();return this.data.products().filter(p=>!q||`${p.name} ${p.reference}`.toLowerCase().includes(q));};
 readonly filteredCustomers=()=>{const q=this.customerQuery.trim().toLowerCase();return this.data.customers().filter(c=>(this.customerType==='Todos'||c.type===this.customerType)&&(this.region()==='Todas'||c.province===this.region())&&(this.customerMinSpend===null||c.annualSpent>=this.customerMinSpend)&&(!q||`${c.name} ${c.email} ${c.city}`.toLowerCase().includes(q)));};
 readonly filteredInvoices=()=>{const q=this.invoiceQuery.trim().toLowerCase();return this.data.invoices().filter(i=>(!q||`${i.number} ${i.customer}`.toLowerCase().includes(q))&&(this.invoiceStatus==='all'||i.status===this.invoiceStatus)&&(!this.invoiceFrom||i.isoDate>=this.invoiceFrom)&&(!this.invoiceTo||i.isoDate<=this.invoiceTo)&&(this.invoiceMin===null||i.total>=this.invoiceMin)&&(this.invoiceMax===null||i.total<=this.invoiceMax));};
 readonly financePoints=()=>{const points=this.data.sales();return this.financeRange==='week'?points.slice(-1):this.financeRange==='month'?points.slice(-1):this.financeRange==='quarter'?points.slice(-3):this.financeRange==='year'?points:points.slice(-6);};
 readonly financeTotals=()=>this.financePoints().reduce((total,point)=>({revenue:total.revenue+point.revenue,expenses:total.expenses+point.expenses,orders:total.orders+point.orders}),{revenue:0,expenses:0,orders:0});
 readonly topProducts=computed(()=>[...this.data.products()].sort((a,b)=>b.sales-a.sales).slice(0,4)); readonly lowStock=computed(()=>this.data.products().filter(p=>p.active&&p.stock-p.reserved<=10)); readonly activeProductsCount=computed(()=>this.data.products().filter(p=>p.active).length); readonly outOfStockCount=computed(()=>this.data.products().filter(p=>this.available(p)===0).length); readonly maximumRevenue=computed(()=>Math.max(...this.data.sales().map(p=>p.revenue),1)); readonly maximumProductSales=computed(()=>Math.max(...this.topProducts().map(p=>p.sales),1)); readonly currentDate=new Intl.DateTimeFormat('es-ES',{weekday:'long',day:'numeric',month:'long'}).format(new Date()); private readonly routeSubscription:Subscription;
 constructor(readonly data:AdminDataService,private readonly route:ActivatedRoute,private readonly router:Router){this.routeSubscription=this.route.paramMap.subscribe(params=>{const requested=params.get('section') as AdminSection|null;this.section.set(this.navItems.some(i=>i.id===requested)?requested!:'overview');this.mobileMenuOpen.set(false);});}
 ngOnDestroy(){this.routeSubscription.unsubscribe();} navigate(section:AdminSection){this.router.navigate(section==='overview'?['/gestion']:['/gestion',section]);}
 statusLabel(status:OrderStatus){return({pendingPayment:'Pendiente de pago',paid:'Pagado',preparing:'En preparación',shipped:'Enviado',delivered:'Entregado',collected:'Recogido en bodega',cancelled:'Cancelado'})[status];} available(p:AdminProduct){return Math.max(0,p.stock-p.reserved);}
 orderCount(status:OrderStatus){return this.data.orders().filter(order=>order.status===status).length;}
 iconPath(name:string){return ({home:'M3 11.5 12 4l9 7.5V21h-6v-6H9v6H3z',orders:'M5 4h14v16H5z M8 8h8 M8 12h8 M8 16h5',bottle:'M10 3h4v4l2 3v11H8V10l2-3z',boxes:'M4 7l8-4 8 4-8 4z M4 7v10l8 4 8-4V7 M12 11v10',users:'M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2 M9 11a4 4 0 1 0 0-8 4 4 0 0 0 0 8 M22 21v-2a4 4 0 0 0-3-3.87 M16 3.13a4 4 0 0 1 0 7.75',chart:'M4 20V10 M10 20V4 M16 20v-7 M22 20H2',calendar:'M5 4h14v17H5z M8 2v4 M16 2v4 M5 9h14',invoice:'M6 3h12v18l-3-2-3 2-3-2-3 2z M9 8h6 M9 12h6 M9 16h3',settings:'M12 15.5a3.5 3.5 0 1 0 0-7 3.5 3.5 0 0 0 0 7 M19.4 15a1.7 1.7 0 0 0 .34 1.88l.06.06-2.12 2.12-.06-.06a1.7 1.7 0 0 0-1.88-.34 1.7 1.7 0 0 0-1 1.55V20h-3v-.09a1.7 1.7 0 0 0-1-1.55 1.7 1.7 0 0 0-1.88.34l-.06.06-2.12-2.12.06-.06A1.7 1.7 0 0 0 6.6 15a1.7 1.7 0 0 0-1.55-1H5v-3h.09a1.7 1.7 0 0 0 1.55-1 1.7 1.7 0 0 0-.34-1.88l-.06-.06L8.36 5.94l.06.06a1.7 1.7 0 0 0 1.88.34 1.7 1.7 0 0 0 1-1.55V4h3v.09a1.7 1.7 0 0 0 1 1.55 1.7 1.7 0 0 0 1.88-.34l.06-.06 2.12 2.12-.06.06a1.7 1.7 0 0 0-.34 1.88 1.7 1.7 0 0 0 1.55 1H21v3h-.09a1.7 1.7 0 0 0-1.51 1z'})[name]??'';}
 nextActions(o:AdminOrder){if(o.payment!=='succeeded')return[];if(o.status==='paid')return[{label:'Pasar a preparación',status:'preparing' as OrderStatus},{label:'Recogido en bodega',status:'collected' as OrderStatus}];if(o.status==='preparing')return[{label:'Marcar como enviado',status:'shipped' as OrderStatus},{label:'Recogido en bodega',status:'collected' as OrderStatus}];if(o.status==='shipped')return[{label:'Confirmar entrega',status:'delivered' as OrderStatus}];return[];}
 openCustomer(c?:AdminCustomer){this.customerDraft=c?{...c}:this.emptyCustomer();this.selectedCustomer.set(c??null);this.customerPanelOpen.set(true);} saveCustomer(){if(!this.customerDraft.name||!this.customerDraft.email)return;this.data.saveCustomer({...this.customerDraft,id:this.customerDraft.id||`local-${Date.now()}`});this.customerPanelOpen.set(false);this.showNotice('Cliente guardado en la vista de demostración.');} openProduct(product?:AdminProduct){this.selectedProductId.set(product?.id??null);this.productDraft=product?{reference:product.reference,name:product.name,category:product.category,price:product.price,vatRate:product.vatRate,stock:product.stock,active:product.active}:this.emptyProduct();this.productPanelOpen.set(true);this.productMenu.set(null);} saveProduct(){if(!this.productDraft.name.trim()||!this.productDraft.reference.trim())return;if(!Number.isFinite(this.productDraft.price)||this.productDraft.price<0||!Number.isInteger(this.productDraft.stock)||this.productDraft.stock<0||!Number.isFinite(this.productDraft.vatRate)||this.productDraft.vatRate<0||this.productDraft.vatRate>100){this.showNotice('Revisa precio, impuesto y stock: no se permiten valores negativos ni unidades decimales.');return;}if(this.data.products().some(p=>p.id!==this.selectedProductId()&&p.reference.toLowerCase()===this.productDraft.reference.trim().toLowerCase())){this.showNotice('Ya existe un producto con esa referencia.');return;}const payload={...this.productDraft,name:this.productDraft.name.trim(),reference:this.productDraft.reference.trim()};const id=this.selectedProductId();if(id)this.data.updateProduct(id,payload);else this.data.addProduct(payload);this.productDraft=this.emptyProduct();this.selectedProductId.set(null);this.productPanelOpen.set(false);this.showNotice(id?'Producto actualizado localmente.':'Producto añadido localmente.');} saveVisit(){if(!this.visitDraft.customer||!this.visitDraft.isoDate)return;this.data.addVisit({...this.visitDraft,id:`local-${Date.now()}`,date:new Intl.DateTimeFormat('es-ES',{day:'numeric',month:'short'}).format(new Date(`${this.visitDraft.isoDate}T12:00:00`))});this.visitPanelOpen.set(false);this.showNotice('Reserva creada en la vista de demostración.');}
 exportData(format:'csv'|'json'){const rows=this.section()==='customers'?this.filteredCustomers():this.section()==='billing'?this.filteredInvoices():this.section()==='finance'?this.financePoints():this.filteredOrders();const body=format==='json'?JSON.stringify(rows,null,2):this.toCsv(rows as unknown as Record<string,unknown>[]);const blob=new Blob([body],{type:format==='json'?'application/json':'text/csv;charset=utf-8'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`dominio-sierra-${this.section()}.${format}`;a.click();URL.revokeObjectURL(url);this.showNotice(`Exportación ${format.toUpperCase()} preparada con los filtros actuales.`);} runGlobalSearch(){const query=this.globalQuery.trim();if(!query){this.searchOpen.set(!this.searchOpen());return;}const normalized=query.toLowerCase();if(this.data.orders().some(o=>`${o.number} ${o.customer} ${o.email}`.toLowerCase().includes(normalized))){this.orderQuery=query;this.navigate('orders');}else if(this.data.customers().some(c=>`${c.name} ${c.email}`.toLowerCase().includes(normalized))){this.customerQuery=query;this.navigate('customers');}else{this.productQuery=query;this.navigate('catalog');}this.searchOpen.set(false);} showNotice(message:string){this.notice.set(message);window.setTimeout(()=>{if(this.notice()===message)this.notice.set('');},3200);} private toCsv(rows:Record<string,unknown>[]){if(!rows.length)return'';const keys=Object.keys(rows[0]).filter(k=>typeof rows[0][k]!=='object');return[keys.join(';'),...rows.map(r=>keys.map(k=>`"${String(r[k]??'').replaceAll('"','""')}"`).join(';'))].join('\n');}
 private emptyProduct():Omit<AdminProduct,'id'|'sales'|'reserved'|'updatedAt'>{return{reference:'',name:'',category:'Tintos',price:0,vatRate:21,stock:0,active:true};}
 private emptyCustomer():AdminCustomer{return{id:'',name:'',email:'',phone:'',city:'',province:'',type:'Particular',orders:0,spent:0,annualSpent:0,lastOrder:'Sin pedidos',segment:'Nuevo',discount:0,notes:'',active:true};}
 private emptyVisit():AdminVisit{return{id:'',customer:'',email:'',type:'Viñedo, bodega y cata',date:'',isoDate:'',time:'11:00',people:2,status:'confirmed',payment:'pending',amount:36,previousVisits:0,notes:''};}
}
