import { Component, HostListener, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { RouterLink } from '@angular/router';

@Component({ selector: 'ds-contact', standalone: true, imports: [RouterLink, FormsModule], template: `
  <section class="contact-hero"><div class="contact-hero-image" aria-hidden="true"></div><div class="shell contact-hero-content"><p class="eyebrow light">Estamos al otro lado</p><h1>Cuéntanos<br><em>qué tienes en mente.</em></h1><p>Una visita, un pedido especial o una mesa que pide Rufete. Escríbenos y empezamos la conversación.</p><div class="contact-hero-actions"><a href="mailto:info@dominiodelasierra.com" class="button button-light">Escribir un correo <span>↗</span></a><a href="tel:+34665144697" class="contact-phone">+34 665 144 697</a></div></div><div class="contact-word" aria-hidden="true">HOLA</div></section>
  <section class="contact-form-wrap"><div class="contact-vine contact-vine-left" aria-hidden="true"></div><div class="contact-vine contact-vine-right" aria-hidden="true"></div><div class="contact-harvest" aria-hidden="true"></div><div class="shell contact-form-section section-pad"><div class="contact-form-copy"><p class="section-kicker">Escríbenos</p><h2>Una conversación<br>que empieza <em>aquí.</em></h2><p>Cuéntanos qué necesitas. La solicitud queda preparada para conectarse al correo de la bodega cuando activemos el servicio.</p><div class="contact-signature"><span>DS</span><p>Respondemos personalmente,<br>normalmente en menos de 48 horas.</p></div></div><form class="contact-form" (ngSubmit)="submitContact()" #contactForm="ngForm"><div class="form-row"><label>Nombre y apellidos<input name="name" [(ngModel)]="form.name" autocomplete="name" required placeholder="Tu nombre"></label><label>Correo electrónico<input name="email" [(ngModel)]="form.email" type="email" autocomplete="email" required placeholder="tu@correo.com"></label></div><label>¿De qué hablamos?<select name="topic" [(ngModel)]="form.topic" required><option value="" disabled>Selecciona una opción</option><option value="visita">Organizar una visita</option><option value="pedido">Pedido o tienda online</option><option value="restauracion">Restauración y distribución</option><option value="otro">Otra consulta</option></select></label><label>Mensaje<textarea name="message" [(ngModel)]="form.message" rows="5" required placeholder="Cuéntanos un poco más..."></textarea></label><label class="privacy-check"><input type="checkbox" name="privacy" [(ngModel)]="form.privacy" required><span>Acepto la <a href="https://dominiodelasierra.com/politica-privacidad/" target="_blank" rel="noopener">política de privacidad</a>.</span></label>@if (sent()) { <div class="contact-success" role="status"><strong>Tu mensaje está listo.</strong><span>Esta demo no envía datos todavía; el formulario queda preparado para conectar el correo.</span></div> } @else { <button class="button button-dark" [disabled]="contactForm.invalid">Enviar consulta <span>↗</span></button> }</form></div></section>
  <section class="shell contact-channels"><div class="contact-intro"><p class="section-kicker">También estamos aquí</p><h2>Cerca, incluso<br>antes de <em>llegar.</em></h2><p>Somos una bodega pequeña. Cuando escribes o llamas, hablas directamente con nosotros.</p></div><div class="contact-channel-grid"><a href="mailto:info@dominiodelasierra.com" class="contact-channel"><span>01 · Correo</span><strong>info&#64;dominiodelasierra.com</strong><i>↗</i><small>Consultas, pedidos y restauración</small></a><a href="tel:+34665144697" class="contact-channel"><span>02 · Teléfono</span><strong>+34 665 144 697</strong><i>↗</i><small>De lunes a viernes · 10:00–18:00</small></a><a routerLink="/visitas" fragment="reservar" class="contact-channel contact-channel-accent"><span>03 · En persona</span><strong>Ven a la bodega</strong><i>↗</i><small>Reserva una experiencia en la Sierra</small></a></div></section>
  <section class="contact-map"><div class="contact-map-photo" aria-hidden="true"></div><div class="real-location-map contact-real-map" role="button" tabindex="0" (click)="mapOpen.set(true)" (keydown.enter)="mapOpen.set(true)" (keydown.space)="mapOpen.set(true); $event.preventDefault()" aria-label="Ampliar mapa de San Esteban de la Sierra"><img src="https://static-maps.yandex.ru/1.x/?lang=es_ES&amp;ll=-5.905,40.506&amp;z=16&amp;l=sat,skl&amp;size=650,450" alt="Vista aérea real de San Esteban de la Sierra"><span class="map-pin-ui" aria-hidden="true"><i></i></span><div class="map-card-label"><span>San Esteban de la Sierra</span><strong>La bodega, en el mapa</strong><small>Haz clic para ampliar ↗</small></div></div><div class="shell"><span>40° 30' N · 5° 54' W</span><strong>San Esteban<br>de la Sierra</strong><p>Salamanca · España</p><a href="https://www.google.com/maps/search/?api=1&amp;query=40.506,-5.905" target="_blank" rel="noopener" class="button button-light">Abrir en Google Maps <span>↗</span></a></div></section>
  @if (mapOpen()) { <div class="map-viewer-backdrop" (click)="mapOpen.set(false)"><section class="map-viewer" role="dialog" aria-modal="true" aria-label="Ubicación de Dominio de la Sierra" (click)="$event.stopPropagation()"><button class="map-viewer-close" type="button" (click)="mapOpen.set(false)" aria-label="Cerrar mapa">×</button><div class="map-viewer-image"><img src="https://static-maps.yandex.ru/1.x/?lang=es_ES&amp;ll=-5.905,40.506&amp;z=16&amp;l=sat,skl&amp;size=650,450" alt="Vista aérea ampliada de San Esteban de la Sierra"><span class="map-pin-ui" aria-hidden="true"><i></i></span></div><div class="map-viewer-copy"><span>40° 30' N · 5° 54' W</span><h2>San Esteban de la Sierra</h2><p>Dominio de la Sierra · Sierra de Francia · Salamanca</p><a class="button button-dark" href="https://www.google.com/maps/search/?api=1&amp;query=40.506,-5.905" target="_blank" rel="noopener">Ir a la dirección <span>↗</span></a></div></section></div> }
`, styles: [] })
export class ContactComponent {
  readonly sent = signal(false);
  readonly mapOpen = signal(false);
  form = { name: '', email: '', topic: '', message: '', privacy: false };
  submitContact(): void { this.sent.set(true); }
  @HostListener('document:keydown.escape') closeMap(): void { this.mapOpen.set(false); }
}
