import { Component } from '@angular/core';
import { RouterLink } from '@angular/router';
import { CatalogService } from '../../core/catalog.service';
import { CartService } from '../../core/cart.service';
import { ProductCardComponent } from '../../shared/product-card.component';

@Component({ selector: 'ds-home', standalone: true, imports: [RouterLink, ProductCardComponent], template: `
  <section class="home-hero"><div class="hero-image"></div><div class="shell hero-content"><p class="eyebrow light">Bodega · San Esteban de la Sierra</p><h1>Nuestra tierra.<br><em>Nuestro carácter.</em></h1><p class="hero-copy">Desde San Esteban de la Sierra, una invitación a descubrir la Rufete y el lugar que le da su identidad.</p><div class="hero-actions"><a routerLink="/vinos" class="button button-light">Descubrir los vinos <span>↗</span></a><a routerLink="/visitas" class="inline-link light-link">Ven a conocernos <span>↓</span></a></div></div><div class="hero-note"><span>San Esteban de la Sierra</span><span>Rufete · Altitud · Tiempo</span></div></section>
  <section class="home-offer shell section-pad"><div class="offer-heading"><div><div class="section-kicker">01 — Desde la bodega</div><h2>Vinos con<br><em>sitio propio.</em></h2></div><div><p class="lead">Rufete, altura y una producción pequeña para que cada botella conserve la voz de San Esteban de la Sierra.</p><a routerLink="/vinos" class="underline-link">Ver la colección completa <span>↗</span></a></div></div><div class="category-grid"><a routerLink="/vinos" class="category-tile category-red"><span>Tintos</span><small>Profundos · Frescos · Rufete</small><b>↗</b></a><a routerLink="/vinos" class="category-tile category-gold"><span>Blancos</span><small>Minerales · Luminosos · De altura</small><b>↗</b></a><a routerLink="/visitas" class="category-tile category-dark"><span>Ven a la bodega</span><small>Una experiencia para beber despacio</small><b>↗</b></a></div></section>
  <section class="story-band"><div class="story-visual"></div><div class="story-copy"><p class="eyebrow">02 — La identidad de la Rufete</p><h2>Una variedad.<br><em>Muchas historias.</em></h2><p>Delicada, fresca y difícil de domesticar. La Rufete lleva siglos leyendo estas laderas y convierte la altura, la piedra y el tiempo en una voz propia.</p><p class="story-note">8.000 botellas al año. Cada parcela por separado. Ningún atajo entre la viña y la copa.</p><a routerLink="/historia" class="button button-outline-light">Conocer nuestra manera <span>↗</span></a></div></section>
  <section class="products-section shell section-pad"><div class="section-head"><div><div class="section-kicker">03 — Selección de la casa</div><h2>Para beber <em>el paisaje.</em></h2></div><span class="muted-note">Vista rápida, detalles y compra sin perder el hilo</span></div>@if (catalog.selectionError(); as message) { <p class="empty-state">{{ message }}</p> }<div class="product-grid">@for (product of catalog.selection(); track product.id) { <ds-product-card [product]="product" [neighbors]="catalog.selection()" (addToCart)="cart.add($event)" /> } @empty { @if (!catalog.selectionLoading() && !catalog.selectionError()) { <p class="empty-state">Todavía no hay vinos publicados.</p> } }</div></section>
  <section class="visit-cta"><div class="visit-cta-photo" aria-hidden="true"></div><div class="visit-cta-shade" aria-hidden="true"></div><div class="shell visit-cta-inner"><div><p class="eyebrow light">Una copa sabe mejor aquí</p><h2>Conoce el origen.<br><em>Comparte una copa.</em></h2><p class="visit-cta-place">San Esteban de la Sierra · Salamanca</p></div><div class="visit-cta-card"><div class="visit-cta-card-head"><span>Experiencia en origen</span><strong>90 minutos para entender la Rufete.</strong></div><p>Camina entre bancales, entra en la bodega y termina alrededor de una cata guiada.</p><div class="visit-cta-meta"><span>Desde 18 €</span><span>Grupos reducidos</span><span>Reserva flexible</span></div><a routerLink="/visitas" fragment="reservar" class="button button-light full-width">Elegir mi visita <span>↗</span></a></div></div></section>
  <section class="numbers-section shell"><div><strong>8K</strong><span>botellas al año</span></div><div><strong>RUFETE</strong><span>nuestra variedad</span></div><div><strong>DO</strong><span> Sierra de Salamanca</span></div><div><strong>Origen</strong><span>San Esteban de la Sierra</span></div></section>
`, styles: [] })
export class HomeComponent {
  constructor(public readonly catalog: CatalogService, public readonly cart: CartService) {}
}
