import { Component } from '@angular/core';
import { RouterLink } from '@angular/router';

@Component({ selector: 'ds-story', standalone: true, imports: [RouterLink], template: `
  <section class="story-page-hero"><div class="shell"><p class="eyebrow light">Nuestra historia</p><h1>Una forma de<br><em>pertenecer.</em></h1><p>La memoria de una sierra contada a través de una variedad única.</p></div></section>
  <section class="editorial-section section-pad"><div class="story-origin-grape" aria-hidden="true"></div><div class="shell"><p class="section-kicker">02 — El origen</p><div class="story-editorial-layout"><div class="story-editorial-image"><span>Rufete · Sierra de Francia</span></div><div class="story-editorial-copy"><h2>La Rufete no se explica.<br><em>Se vive.</em></h2><p class="lead">En San Esteban de la Sierra, la montaña no es un telón de fondo. Es el trabajo, la luz, la pendiente y la memoria.</p><p>Dominio de la Sierra nace de la voluntad de recuperar el pulso de una uva propia. La Rufete es delicada, nerviosa y expresiva; pide paciencia y devuelve una identidad que no se parece a ninguna otra.</p><p>Por eso hacemos pocas botellas. Porque cada parcela necesita su tiempo y cada vino debe llevar consigo el lugar del que viene.</p></div></div></div></section>
  <section class="manifesto-band"><div class="manifesto-grape" aria-hidden="true"></div><div class="shell manifesto-feature"><div class="manifesto-photo" aria-hidden="true"><span>Método ancestral · Rufete</span></div><div class="manifesto-intro"><p class="eyebrow light">Nuestro compromiso</p><h2>Hacer menos.<br><em>Decir más.</em></h2><p>No perseguimos el volumen. Buscamos que cada botella sea reconocible, honesta y profundamente serrana. También en nuestro Rufete ancestral: burbuja natural, una sola fermentación y la forma más viva de recordar cómo se hacía el vino antes.</p><div class="manifesto-process"><span>Vendimia manual</span><span>Prensado suave</span><span>Una fermentación</span></div></div></div><div class="shell manifesto-grid"><div><span>01</span><h3>Origen antes que volumen.</h3><p>8.000 botellas para cuidar cada detalle y respetar el ritmo de cada parcela.</p></div><div><span>02</span><h3>Tradición con mirada propia.</h3><p>Saberes antiguos, decisiones precisas y una bodega abierta a seguir aprendiendo.</p></div><div><span>03</span><h3>El paisaje en la copa.</h3><p>Altitud, piedra, frescura y Rufete: el carácter de la Sierra sin disfraces.</p></div></div></section>
  <section class="story-end"><div class="story-end-photo" aria-hidden="true"></div><div class="shell story-end-inner"><p class="eyebrow light">Ven a conocerlo</p><h2>La historia cambia<br>cuando la <em>visitas.</em></h2><p>Camina las viñas, entra en la bodega y comparte una copa con quienes la hacen posible.</p><a routerLink="/visitas" fragment="reservar" class="button button-light">Reserva tu visita <span>↗</span></a></div></section>
`, styles: [] })
export class StoryComponent {}
